### ISSUE TITLE
.github dir issue 

### ISSUE THREAD

**Issue by PowerLevel9000** [mertkantaroglu/todo-list-with-react#2]
# linters not working

hi @mertkantaroglu 

##  great job while working on the tutorial projects look nice 

- [ ] it's just and fast forward issue we don't have live link so I didn't check project 

## .github folder

- [x] kindly change the name of your root github folder to .github this will fix your problem however if you still face the problem
you can delete the folder and commit again then add folder again hopefully this will fix the linter problem 

## happy coding mate 

![CoolGIF](https://user-images.githubusercontent.com/116451144/223331801-0a53672f-deb0-401a-93fd-e7de9cd7b476.gif)

**Comment by mertkantaroglu** [comment]
Thanks a lot @PowerLevel9000 for your suggestion. It worked and everything works fine right now.

![Thumbs up](https://user-images.githubusercontent.com/44959066/223333658-423457ad-a998-4006-9fc9-50ba6ae10d65.gif)
